language: python
python: "2.7"
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=4.2
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis-${PLONE_VERSION}.cfg
  - bin/buildout -c travis-${PLONE_VERSION}.cfg install download
  - bin/buildout -c travis-${PLONE_VERSION}.cfg install install
  - bin/buildout -N -t 3 -c travis-${PLONE_VERSION}.cfg
script: bin/test
